behaviors:
  3DBall:

    trainer_type: ppo

    hyperparameters:
      batch_size: {{batch_size}}
      buffer_size: {{buffer_size}}
      learning_rate: {{learning_rate}}
      beta: {{beta}}
      epsilon: {{epsilon}}
      lambd: {{lambd}}
      num_epoch: {{num_epoch}}
      learning_rate_schedule: {{learning_rate_schedule}}

    network_settings:
      normalize: {{normalize}}
      hidden_units: {{hidden_units}}
      num_layers: {{num_layers}}
      vis_encode_type: {{vis_encode_type}}

    reward_signals:
      extrinsic:
        gamma: {{gamma}}
        strength: {{strength}}

    keep_checkpoints: {{keep_checkpoints}}
    max_steps: {{max_steps}}
    time_horizon: {{time_horizon}}
    summary_freq: {{summary_freq}}
