[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Group8-pipeline"
version = "1.0"
description = "MLAgents training with monitoring and result tracking"
authors = [{ name = "Group 8" }]

dependencies = ["mlagents", "psutil", "onnx"]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["builds*", "experiments*"]


[project.scripts]
mlrun = "training_pipeline.cli.run_experiment:main"
predrun = "prediction_models.cli.run_predictions:main"
