behaviors:
  3DBall:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 640
      learning_rate: 0.00020469802812511477
      beta: 0.005775616047335888
      epsilon: 0.10778934960489035
      lambd: 0.906761843237523
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.8639636594237547
        strength: 1
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 10000
